name: app
description: my cat is better than yours
version: 1.0.1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  angular: ^5.1.0
  angular_forms: ^2.1.0
  angular_router: ^2.0.0-alpha+20
  angular_components: ^0.10.1
  string_converters: ^1.0.0
  font_awesome: 4.7.0+1
  chartjs: ^0.5.0
  md_bootstrap_scss:
    git: https://github.com/dart-land/md_bootstrap_scss
  tlm_paper:
    git: https://github.com/Dart-Land/tlm_paper.git
  tlmThemeLogic:
    git: https://gitlab.com/trhhosting/tlmThemeLogic.git
dev_dependencies:
  analyzer: ^0.33.0
  test: ^1.5.1
  angular_test: ^2.1.0
  build_test: ^0.10.3+3
  build_runner: ^1.1.2
  build_web_compilers: ^0.4.4+2
  sass_builder: ^2.1.2
